# Import bibliotek.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

# Tensory - tworzenie.

## Skalar.

In [2]:
scalar = 3
print(scalar)
print(type(scalar))

3
<class 'int'>


In [3]:
scalar = 3.00
print(scalar)
print(type(scalar))

3.0
<class 'float'>


## Wektor.

In [4]:
vector = np.array([1, 2, 3])
print(vector)
print(type(vector))
print(f"Rozmiar wektora: {vector.shape}")
print(f"Typ danych wektora: {vector.dtype}")
print(f"Rząd wektora: {vector.ndim}")
print(f"Długość wektora: {len(vector)}")

[1 2 3]
<class 'numpy.ndarray'>
Rozmiar wektora: (3,)
Typ danych wektora: int64
Rząd wektora: 1
Długość wektora: 3


In [5]:
vector = np.array([1, 2, 3], dtype=np.float32)
print(vector)
print(f"Typ danych wektora: {vector.dtype}")

[1. 2. 3.]
Typ danych wektora: float32


## Macierz.

In [6]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
print(f"Rozmiar macierzy: {array.shape}")
print(f"Typ danych macierzy: {array.dtype}")
print(f"Rząd macierzy: {array.ndim}")
print(f"Długość macierzy: {len(array)}")

[[1 2 3]
 [4 5 6]]
Rozmiar macierzy: (2, 3)
Typ danych macierzy: int64
Rząd macierzy: 2
Długość macierzy: 2


In [7]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float32)
print(array)
print(f"Rozmiar macierzy: {array.shape}")
print(f"Typ danych macierzy: {array.dtype}")
print(f"Rząd macierzy: {array.ndim}")
print(f"Długość macierzy: {len(array)}")

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Rozmiar macierzy: (3, 3)
Typ danych macierzy: float32
Rząd macierzy: 2
Długość macierzy: 3


## Tensor.

Tensor jest uogólnieniem macierzy na wyższe wymiary. Jest on potrzebny do zapisywania danych takich, jak obraz lub film.

In [8]:
tensor = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [10, 11, 12]]
])
print(tensor)
print(f"Rozmiar macierzy: {tensor.shape}")
print(f"Typ danych macierzy: {tensor.dtype}")
print(f"Rząd macierzy: {array.ndim}")
print(f"Długość macierzy: {len(array)}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Rozmiar macierzy: (2, 2, 3)
Typ danych macierzy: int64
Rząd macierzy: 2
Długość macierzy: 3


In [9]:
tensor = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [10, 11, 12]],
    [[13, 14, 15],
     [16, 17, 18]]
], dtype=np.float32)
print(tensor)
print(f"Rozmiar macierzy: {tensor.shape}")
print(f"Typ danych macierzy: {tensor.dtype}")
print(f"Rząd macierzy: {array.ndim}")
print(f"Długość macierzy: {len(array)}")

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]

 [[13. 14. 15.]
  [16. 17. 18.]]]
Rozmiar macierzy: (3, 2, 3)
Typ danych macierzy: float32
Rząd macierzy: 2
Długość macierzy: 3


In [10]:
tensor = np.array([
    [[1, 2, 3, 4],
     [4, 5, 6, 4],
     [4, 2, 5, 2]],
    [[7, 8, 9, 8],
     [3, 7, 3, 9],
     [5, 2, 4, 3]],
    [[2, 3, 5, 4],
     [7, 2, 5, 1],
     [8, 2, 7, 2]],
    [[2, 3, 5, 7],
     [7, 2, 5, 9],
     [8, 2, 7, 0]],
    [[2, 3, 5, 7],
     [7, 2, 5, 9],
     [8, 2, 7, 0]]
])

print(tensor)
print(type(tensor))
print(f'Rozmiar macierzy: {tensor.shape}')
print(f'Typ danych macierzy: {tensor.dtype}')
print(f'Rząd: {tensor.ndim}')
print(f'Długosc: {len(tensor)}')

[[[1 2 3 4]
  [4 5 6 4]
  [4 2 5 2]]

 [[7 8 9 8]
  [3 7 3 9]
  [5 2 4 3]]

 [[2 3 5 4]
  [7 2 5 1]
  [8 2 7 2]]

 [[2 3 5 7]
  [7 2 5 9]
  [8 2 7 0]]

 [[2 3 5 7]
  [7 2 5 9]
  [8 2 7 0]]]
<class 'numpy.ndarray'>
Rozmiar macierzy: (5, 3, 4)
Typ danych macierzy: int64
Rząd: 3
Długosc: 5


# Funkcje aktywacji.

## ReLU.

Wzór:

 $$f(x) = max(x, 0)$$

In [11]:
def max_relu(x):
    return max(0., x)

In [12]:
for i in range(-10, 10, 2):
    print(f"ReLU({i}) = {max_relu(i)}")

ReLU(-10) = 0.0
ReLU(-8) = 0.0
ReLU(-6) = 0.0
ReLU(-4) = 0.0
ReLU(-2) = 0.0
ReLU(0) = 0.0
ReLU(2) = 2
ReLU(4) = 4
ReLU(6) = 6
ReLU(8) = 8


In [13]:
np.random.seed(42)
data = np.random.randn(50)
data = sorted(data)
data

[-1.9596701238797756,
 -1.913280244657798,
 -1.763040155362734,
 -1.7249178325130328,
 -1.4785219903674274,
 -1.4247481862134568,
 -1.4123037013352915,
 -1.3281860488984305,
 -1.2208436499710222,
 -1.1509935774223028,
 -1.0577109289559004,
 -1.0128311203344238,
 -0.9080240755212109,
 -0.7198442083947086,
 -0.6017066122293969,
 -0.600638689918805,
 -0.5622875292409727,
 -0.5443827245251827,
 -0.4694743859349521,
 -0.46572975357025687,
 -0.46341769281246226,
 -0.4606387709597875,
 -0.3011036955892888,
 -0.2916937497932768,
 -0.23415337472333597,
 -0.23413695694918055,
 -0.22577630048653566,
 -0.13826430117118466,
 -0.11564828238824053,
 -0.013497224737933921,
 0.06752820468792384,
 0.11092258970986608,
 0.1713682811899705,
 0.19686123586912352,
 0.2088635950047554,
 0.24196227156603412,
 0.3142473325952739,
 0.3436182895684614,
 0.37569801834567196,
 0.4967141530112327,
 0.5425600435859647,
 0.6476885381006925,
 0.7384665799954104,
 0.7674347291529088,
 0.822544912103189,
 1.057122226218

In [14]:
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.067528, 0.110923, 0.171368, 0.196861, 0.208864, 0.241962,
       0.314247, 0.343618, 0.375698, 0.496714, 0.54256 , 0.647689,
       0.738467, 0.767435, 0.822545, 1.057122, 1.465649, 1.52303 ,
       1.579213, 1.852278])

In [15]:
df = pd.DataFrame({'x': data, 'relu(x)': max_relu_data})
df.head(10)

x  relu(x)
0 -1.959670      0.0
1 -1.913280      0.0
2 -1.763040      0.0
3 -1.724918      0.0
4 -1.478522      0.0
5 -1.424748      0.0
6 -1.412304      0.0
7 -1.328186      0.0
8 -1.220844      0.0
9 -1.150994      0.0

In [16]:
df.tail(10)

x   relu(x)
40  0.542560  0.542560
41  0.647689  0.647689
42  0.738467  0.738467
43  0.767435  0.767435
44  0.822545  0.822545
45  1.057122  1.057122
46  1.465649  1.465649
47  1.523030  1.523030
48  1.579213  1.579213
49  1.852278  1.852278

In [17]:
px.line(df, x='x', y='relu(x)', width=700, height=500, title='ReLU')

## Sigmoid.

Wzór:

$$f(x) = \frac{1}{1 + e^{-x}}$$

In [18]:
def sigmoid(x):
    return(1 / (1 + np.exp(-x)))

In [19]:
for i in range(-10, 10, 2):
    print(f"Sigmoid({i}) = {sigmoid(i)}")

Sigmoid(-10) = 4.5397868702434395e-05
Sigmoid(-8) = 0.0003353501304664781
Sigmoid(-6) = 0.0024726231566347743
Sigmoid(-4) = 0.01798620996209156
Sigmoid(-2) = 0.11920292202211755
Sigmoid(0) = 0.5
Sigmoid(2) = 0.8807970779778823
Sigmoid(4) = 0.9820137900379085
Sigmoid(6) = 0.9975273768433653
Sigmoid(8) = 0.9996646498695336


In [20]:
data = [i * 3 for i in data]
data

[-5.8790103716393265,
 -5.739840733973393,
 -5.289120466088201,
 -5.174753497539099,
 -4.435565971102282,
 -4.274244558640371,
 -4.236911104005874,
 -3.9845581466952913,
 -3.6625309499130667,
 -3.4529807322669086,
 -3.173132786867701,
 -3.0384933610032716,
 -2.724072226563633,
 -2.159532625184126,
 -1.8051198366881906,
 -1.801916069756415,
 -1.686862587722918,
 -1.633148173575548,
 -1.4084231578048563,
 -1.3971892607107705,
 -1.3902530784373868,
 -1.3819163128793626,
 -0.9033110867678664,
 -0.8750812493798303,
 -0.7024601241700079,
 -0.7024108708475416,
 -0.677328901459607,
 -0.41479290351355397,
 -0.34694484716472157,
 -0.04049167421380176,
 0.2025846140637715,
 0.33276776912959827,
 0.5141048435699115,
 0.5905837076073706,
 0.6265907850142662,
 0.7258868146981023,
 0.9427419977858216,
 1.0308548687053842,
 1.1270940550370159,
 1.490142459033698,
 1.627680130757894,
 1.9430656143020775,
 2.215399739986231,
 2.3023041874587262,
 2.467634736309567,
 3.171366678656747,
 4.396946306764662

In [21]:
sigmoid_data = [sigmoid(x) for x in data]
sigmoid_data

[0.0027897479765483985,
 0.0032049754250426123,
 0.005020860360958408,
 0.005625782864176061,
 0.011709618427986372,
 0.013731386343115009,
 0.014246274698901138,
 0.01826099469413797,
 0.025025135523921403,
 0.03068009177288235,
 0.04018939642031793,
 0.04571685569013667,
 0.06156776402302208,
 0.10344378924802143,
 0.14122897262519657,
 0.1416179830141327,
 0.15618888609789963,
 0.16339954930005823,
 0.19648288490947172,
 0.19826251217851384,
 0.19936735739137745,
 0.20070140783734772,
 0.28837054357653585,
 0.294198100806427,
 0.3312670124982483,
 0.33127792363701036,
 0.33685772461236896,
 0.3977634315445482,
 0.4141234832174299,
 0.48987846432740595,
 0.550473649382998,
 0.5824326649177111,
 0.6257682515448985,
 0.6434990641134543,
 0.6517160317116847,
 0.6739020142050344,
 0.7196531952955414,
 0.7370815963933136,
 0.7553022186261329,
 0.816099653938776,
 0.8358515920572324,
 0.8746885469942848,
 0.9016239139753182,
 0.9090676910894468,
 0.921841518197807,
 0.9597424220018745,
 0.

In [22]:
df = pd.DataFrame({'x': data, 'sigmoid(x)': sigmoid_data})
df.head(10)

x  sigmoid(x)
0 -5.879010    0.002790
1 -5.739841    0.003205
2 -5.289120    0.005021
3 -5.174753    0.005626
4 -4.435566    0.011710
5 -4.274245    0.013731
6 -4.236911    0.014246
7 -3.984558    0.018261
8 -3.662531    0.025025
9 -3.452981    0.030680

In [23]:
df.tail(10)

x  sigmoid(x)
40  1.627680    0.835852
41  1.943066    0.874689
42  2.215400    0.901624
43  2.302304    0.909068
44  2.467635    0.921842
45  3.171367    0.959742
46  4.396946    0.987835
47  4.569090    0.989739
48  4.737638    0.991317
49  5.556835    0.996154

In [24]:
px.line(df, x='x', y='sigmoid(x)', width=700, height=500, title='Sigmoid')

# Tanh (tangens hiperboliczny).

Wzór:

$$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [25]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [26]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[-5.239490208179489,
 -3.9751378292017856,
 -3.837542430598083,
 -3.214966469122455,
 -3.1013268621322654,
 -2.927029896264237,
 -2.8307414841008285,
 -2.8037021255845618,
 -2.6409132261685526,
 -2.473901421756164,
 -2.4617286328679104,
 -2.3924132481613416,
 -2.337356075239064,
 -2.2126699480120564,
 -2.1246074274522098,
 -1.9810726502613767,
 -1.8388484684676063,
 -1.8187749095894779,
 -1.678435046445277,
 -1.6169872057863752,
 -1.6045545384432378,
 -1.5665065846724742,
 -1.4041061877547047,
 -1.3538440006119175,
 -1.2902395092102485,
 -1.1325954592055438,
 -1.0595204075340776,
 -1.0365404365472948,
 -1.0069513082323984,
 -1.003514087169073,
 -0.9583484756905799,
 -0.8412906455307181,
 -0.7842163062643153,
 -0.7701645608326331,
 -0.685429033053539,
 -0.6553242931955364,
 -0.6441230324113512,
 -0.6184247517024292,
 -0.5980147009317349,
 -0.46917426675029383,
 -0.43934377567502386,
 -0.38472192956224505,
 -0.37131795332763423,
 -0.32257142333201827,
 -0.14889183153233443,
 -0.144020243

In [27]:
tanh_data = [tanh(x) for x in data]
tanh_data

[-0.9999437588215528,
 -0.9992951185890159,
 -0.9990719285402151,
 -0.9967800743761625,
 -0.9959600725710325,
 -0.9942799443093395,
 -0.993069387680434,
 -0.9926856780022238,
 -0.9898851388383544,
 -0.9859021020341189,
 -0.9855571774483821,
 -0.9834273274908996,
 -0.9815160028604687,
 -0.9763428948963355,
 -0.9718509642094404,
 -0.9626656595691097,
 -0.950684488195855,
 -0.9487161328539017,
 -0.9326581737301376,
 -0.9241859331566953,
 -0.9223512651732684,
 -0.9164683020619017,
 -0.8862359908553797,
 -0.8749575479751652,
 -0.859189253151698,
 -0.8119056843095783,
 -0.7854802343236734,
 -0.776518238072782,
 -0.7644981065462144,
 -0.7630660371345719,
 -0.7435392957858745,
 -0.6864920682618905,
 -0.6551200999593222,
 -0.6470251294641565,
 -0.5950375033652043,
 -0.5752433352223086,
 -0.5677003390011902,
 -0.5500302973704034,
 -0.5356353663605714,
 -0.4375318964141261,
 -0.4131003513640145,
 -0.36680115403984936,
 -0.35514397464975916,
 -0.3118301621180942,
 -0.1478012512833392,
 -0.14303268

In [28]:
df = pd.DataFrame({'x': data, 'tanh(x)': tanh_data})
df.head(10)

x   tanh(x)
0 -5.239490 -0.999944
1 -3.975138 -0.999295
2 -3.837542 -0.999072
3 -3.214966 -0.996780
4 -3.101327 -0.995960
5 -2.927030 -0.994280
6 -2.830741 -0.993069
7 -2.803702 -0.992686
8 -2.640913 -0.989885
9 -2.473901 -0.985902

In [29]:
df.tail(10)

x   tanh(x)
90  2.614286  0.989335
91  2.712480  0.991228
92  2.805589  0.992713
93  2.955788  0.994599
94  3.076073  0.995751
95  3.099869  0.995948
96  3.129287  0.996179
97  3.772372  0.998943
98  4.380911  0.999687
99  4.926484  0.999895

In [30]:
px.line(df, x='x', y='tanh(x)', width=700, height=500, title='Tanh')

## Softmax.

Wzór:

   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

In [31]:
def softmax(x):
    e_x = np.exp(x)
    denominator = np.sum(e_x, axis=1)
    denominator = denominator[:, np.newaxis]
    return e_x / denominator

In [32]:
data = np.random.randn(4, 5)
data

array([[ 0.250493,  0.346448, -0.680025,  0.232254,  0.293072],
       [-0.714351,  1.865775,  0.473833, -1.191303,  0.656554],
       [-0.974682,  0.787085,  1.158596, -0.820682,  0.963376],
       [ 0.412781,  0.82206 ,  1.896793, -0.245388, -0.753736]])

In [33]:
result = softmax(data)
result

array([[0.221215, 0.243494, 0.087236, 0.217217, 0.230838],
       [0.045373, 0.59887 , 0.148874, 0.028162, 0.178721],
       [0.042777, 0.249079, 0.361146, 0.049899, 0.297098],
       [0.129106, 0.194399, 0.569435, 0.066851, 0.04021 ]])

In [34]:
result.sum(axis=1)

array([1., 1., 1., 1.])

# Funkcje straty.

## Entropia rozkładu prawdopodobieństwa.

Wzór:

$$Entropia = - \sum_{i}p_{i} * log(p_{i})$$

Gdzie $p_{i}$ to prawdopodobieństwo zajścia $i$-tego zdarzenia.

In [35]:
def entropy(labels, base=None):
    n_labels = len(labels)

    if n_labels <= 1:
        return 0

    value, counts = np.unique(labels, return_counts=True)
    probs = counts / n_labels
    n_classes = np.count_nonzero(probs)

    if n_classes <= 1:
        return 0

    ent = 0.0

    base = math.e if base is None else base
    for i in probs:
        ent -= i * math.log(i, base)
    return ent

labels = [1, 3, 4, 2, 3, 5, 3, 2, 5, 1, 4, 5]
entropy(labels)

1.5890269151739727

In [36]:
labels = [1, 1, 1, 1, 1]
entropy(labels)

0

In [37]:
labels = [1, 1, 1, 1, 2]
entropy(labels)

0.5004024235381879

## Binarna entropia krzyżowa.

Wzór:
$$Binary\ CrossEntropy = - \frac{1}{N}\sum_{i=1}^{N}(y_{i}*log(p(y_{i})) + (1-y_{i}) * log(1-p(y_{i}))$$

In [38]:
def binary_cross_entropy(y_true, y_pred):
    epsilon = 1e-12  # Mała wartość zapobiegająca problemom numerycznym
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    loss = -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
    return loss

In [39]:
y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([0.6, 0.3, 0.8, 0.7, 0.2, 0.9])
binary_cross_entropy(y_true, y_pred)

0.29597052165495025

In [40]:
y_true = np.array([1, 0, 1, 1, 0, 1], dtype='float')
y_pred = np.array([0, 0, 1, 1, 0, 1], dtype='float')

binary_cross_entropy(y_true, y_pred)

4.605170185988923

## Kategoryczna entropia krzyżowa.

Wzór:

$$Categorical\ CrossEntropy= - \sum_{i}y_{i} * log(p(y_{i})) $$

In [41]:
def categorical_crossentropy(y_true, y_pred):
    epsilon = 1e-12
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    loss = -np.sum(y_true * np.log(y_pred)) / y_true.shape[0]
    return loss

In [42]:
y_true = np.array([1, 0, 1, 1, 2, 0, 1, 1, 2], dtype='float')
y_pred = np.array([0, 0, 1, 1, 2, 0, 1, 2, 2], dtype='float')

categorical_crossentropy(y_true, y_pred)

3.070113457326283

In [43]:
y_true = np.array([0, 0, 1, 1, 2, 0, 1, 1, 2], dtype='float')
y_pred = np.array([0, 1, 1, 2, 0, 1, 1, 2, 1], dtype='float')

categorical_crossentropy(y_true, y_pred)

6.140226914651453