In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
# model sekwencyjny - liniowy stos warstw

from tensorflow.keras.models import Sequential

model = Sequential()
model

<Sequential name=sequential, built=False>

In [3]:
# podstawowy element modelu - warstwy
# warstwa wejściowa - Input
# standardowa warstwa gęsto połączona - Dense
# klasę do stosu dodajemy metodą add()

from tensorflow.keras.layers import Dense, Input

model.add(Input(shape=(10,)))
model.add(Dense(units=4)) # units - liczba neuronów
model

<Sequential name=sequential, built=True>

In [4]:
model.summary() # wyświetlenie podsumowania modelu

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 4)                   │              44 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

In [5]:
# dodanie kolejnej warstwy

model.add(Dense(units=2)) # nie podajemy rozmiaru danych wejściowych
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 4)                   │              44 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 2)                   │              10 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 4)                   │              44 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 2)                   │              10 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
# funkcje aktywacji
# odpowiadają za aktywowanie odpowiednich neuronów podczas uczenia
# jeżeli nie określamy f. aktywacji, domyślnie stosowana jest funkcja liniowa
# aby rozwiązywać problemy nieliniowe, stosuje się funkcje inne niż liniowa

from tensorflow.keras.activations import linear

random_data = sorted(np.random.randn(1000))
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -2.945486 -2.945486
1 -2.926548 -2.926548
2 -2.751397 -2.751397
3 -2.699644 -2.699644
4 -2.683651 -2.683651

In [8]:
px.line(data, x='data', y='linear', width=800, range_y=[-2, 2])

In [9]:
# funkcja ReLU - zeruje wartości ujemne

from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -2.945486   0.0
1 -2.926548   0.0
2 -2.751397   0.0
3 -2.699644   0.0
4 -2.683651   0.0

In [10]:
data.tail()

data      relu
995  2.618925  2.618925
996  2.626477  2.626477
997  2.633242  2.633242
998  2.656374  2.656374
999  3.132160  3.132160

In [11]:
px.line(data, x='data', y='relu', width=800, range_y=[-0.5, 1.5])

In [12]:
# funkcja sigmoid - sprowadza dane do przedziału od 0 do 1

from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -2.945486  0.049950
1 -2.926548  0.050857
2 -2.751397  0.060008
3 -2.699644  0.062994
4 -2.683651  0.063945

In [13]:
px.line(data, x='data', y='sigmoid', width=800, range_y=[-0.5, 1.5])

In [14]:
# funkcja tanh - sprowadza dane do przedziału od -1 do 1

from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -2.945486 -0.994487
1 -2.926548 -0.994274
2 -2.751397 -0.991882
3 -2.699644 -0.991001
4 -2.683651 -0.990710

In [15]:
px.line(data, x='data', y='tanh', width=800, range_y=[-1.5, 1.5])

In [16]:
# budowa całego modelu

model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=4, activation='sigmoid'))
# funkcje aktywacji można też dodać jako warstwę typu Activation
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 8)                   │              88 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 4)                   │              36 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 124 (496.00 B)

 Trainable params: 124 (496.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
# kompilacja modelu
# musimy przypisać modelowi optymalizator, funkcję straty i metrykę do obserwacji uczenia
# optymalizator możemy dobierać dowolnie, natomiast f. straty i metrykę odpowiednią dla zadania

# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse') # nie trzeba przekazywać metryki - będzie ta sama, co f. straty

In [18]:
# trening modelu - parametry przekazywane metodzie fit:
# epochs - krotność przejścia danych przez sieć podczas uczenia
# batch_size - rozmiar wsadu, po którym wagi są aktualizowane
# validation_split - część danych treningowych wykorzystywanych jako zbiór walidacyjny
# validation_data - dane wykorzystywane do walidacji (X_val, y_val)

# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

In [19]:
# klasyfikacja binarna

data = np.random.randn(1000, 150)
labels = np.random.randint(0, 2, 1000)
print(data.shape)
print(labels.shape)

(1000, 150)
(1000,)


In [20]:
data[:3]

array([[-5.79239091e-01, -6.44163627e-02,  4.06391900e-01,
        -2.46484568e-01,  2.68530662e-01,  3.28423759e-01,
         1.88688692e+00,  1.33586804e+00,  9.65943161e-02,
         9.36093862e-01, -6.19638273e-01,  4.60426953e-01,
         2.23411323e-01, -3.82217253e-01, -2.97487958e-01,
        -7.93330308e-01, -8.01562575e-01,  5.03361661e-01,
         1.02933213e+00, -7.92707689e-01,  6.38385484e-01,
         6.97627852e-01, -1.19582322e+00,  1.44753320e+00,
         3.03284050e-01, -1.58743143e+00,  8.96942837e-01,
         1.32039082e+00, -8.00589855e-01,  6.72759820e-01,
         2.42698435e+00, -1.33975964e-01,  5.19332335e-01,
         3.71610239e-01,  2.31661699e+00,  2.67333308e-01,
        -4.35020987e-01, -1.44259008e+00,  2.06606474e+00,
         1.89098585e+00,  6.09202035e-01, -3.41362021e-01,
        -9.86552674e-02,  2.36907621e-01, -8.60933741e-01,
        -5.87968335e-01, -4.72397871e-01,  7.51373013e-01,
        -5.99746318e-04,  3.21922838e-01, -2.47226868e-0

In [21]:
labels[:10]

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 1])

In [22]:
model = Sequential()
model.add(Input(shape=(150,))) # warstwa Input nie posiada f. aktywacji
model.add(Dense(units=32, activation='relu'))
# kształt danych wejściowych musi odpowiadać liczbie zmiennych
model.add(Dense(units=1, activation='sigmoid'))
# dla klasyfikacji binarnej na wyjściu dajemy warstwę gęsto połączoną z jednym neuronem
# i sigmoidalną f. aktywacji

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5127 - loss: 0.7920
Epoch 2/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5718 - loss: 0.6976
Epoch 3/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6172 - loss: 0.6633
Epoch 4/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6385 - loss: 0.6254
Epoch 5/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7040 - loss: 0.5859
Epoch 6/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7187 - loss: 0.5667
Epoch 7/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7568 - loss: 0.5394
Epoch 8/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7789 - loss: 0.5232
Epoch 9/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8068 - loss: 0.4869
Epoch 10/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8163 - loss: 0.4711
Epoch 11/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.4612
Epoch 12/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8606 - lo

In [23]:
model = Sequential()
model.add(Input(shape=(150,)))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))


model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)
# dodajemy parametr batch_size dla modyfikacji częstości aktualizacji wag
# validation_split dla podziału na zbiór uczący i walidacyjny
# wyświetlają się nam wtedy również metryki na zbiorze walidacyjnym

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.4983 - loss: 0.8001 - val_accuracy: 0.5900 - val_loss: 0.7216
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5759 - loss: 0.7105 - val_accuracy: 0.5950 - val_loss: 0.7124
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5987 - loss: 0.6672 - val_accuracy: 0.5850 - val_loss: 0.7033
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6447 - loss: 0.6164 - val_accuracy: 0.5600 - val_loss: 0.7053
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7032 - loss: 0.5975 - val_accuracy: 0.5600 - val_loss: 0.7050
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7494 - loss: 0.5583 - val_accuracy: 0.5650 - val_loss: 0.7104
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7647 - loss: 0.5365 - val_accuracy: 0.5450 - val_loss: 0.7148
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7965 - loss: 0.5230 - val_accuracy: 0.5400 - val_loss

In [24]:
model = Sequential()
model.add(Input(shape=(150,)))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))


model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)
# parametr verbose=0 spowoduje brak wyświetlenia outputu
# metoda fit zwraca obiekt typu History

In [25]:
model = Sequential()
model.add(Input(shape=(150,)))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))


model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)
# zmienna history przechowuje nam dane z przebiegu trenowania

In [26]:
# możemy na podstawie tych danych stworzyć obiekt DataFrame lub wykres

metrics = pd.DataFrame(history.history)
metrics.head()

accuracy      loss  val_accuracy  val_loss
0   0.48375  0.799781         0.505  0.806457
1   0.54125  0.712512         0.500  0.783453
2   0.60000  0.663092         0.515  0.770070
3   0.65875  0.622755         0.520  0.767000
4   0.69125  0.588663         0.520  0.761421

In [27]:
model = Sequential()
model.add(Input(shape=(150,)))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))


model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.5235 - loss: 0.7768 - val_accuracy: 0.5300 - val_loss: 0.7947
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5744 - loss: 0.6800 - val_accuracy: 0.5400 - val_loss: 0.7694
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6229 - loss: 0.6512 - val_accuracy: 0.5400 - val_loss: 0.7571
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6824 - loss: 0.6087 - val_accuracy: 0.5400 - val_loss: 0.7479
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6868 - loss: 0.5853 - val_accuracy: 0.5200 - val_loss: 0.7456
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7285 - loss: 0.5551 - val_accuracy: 0.5250 - val_loss: 0.7467
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7602 - loss: 0.5355 - val_accuracy: 0.5300 - val_loss: 0.7466
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7923 - loss: 0.5122 - val_accuracy: 0.5250 - val_loss

In [28]:
# tworzymy dane testowe

test_data = np.random.randn(5, 150)
test_labels = np.random.randint(0, 2, 5)
print(test_data.shape)
print(test_labels.shape)

(5, 150)
(5,)


In [29]:
# używamy funkcji predict
# zwraca ona prawdopodobieństwo przypisania do klasy 1

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step


array([[0.5592317 ],
       [0.207053  ],
       [0.8857412 ],
       [0.7612973 ],
       [0.75743335]], dtype=float32)

In [30]:
# klasyfikacja wieloklasowa

data = np.random.randn(1000, 150)
labels = np.random.randint(0, 10, 1000)
print(data.shape)
print(labels.shape)

(1000, 150)
(1000,)


In [31]:
data[:3]

array([[ 8.71587713e-01, -5.52737136e-01, -1.02666463e-01,
        -1.81020095e-01,  1.84591460e+00, -1.82382766e+00,
         1.41732338e+00,  6.27826228e-01, -4.79840242e-01,
         1.39160285e+00, -6.55034224e-01,  9.12049404e-02,
         3.03690770e+00,  1.22478172e+00,  1.63486068e-01,
         1.47684397e+00,  2.13344344e-01, -1.33632658e-01,
         7.66505876e-01,  7.67495734e-01,  7.79958532e-01,
         1.18666372e+00,  1.22311696e+00, -4.85580973e-01,
        -8.67715943e-01,  2.25602719e-02, -1.81766517e+00,
        -1.18350069e-01, -6.03189440e-01, -2.49617488e-01,
        -1.17109007e+00, -6.69645126e-01, -8.24484512e-01,
        -8.77719943e-02,  8.21388386e-01,  1.02420751e+00,
        -3.26367503e-01,  5.35536202e-01,  4.50423224e-01,
        -3.59086635e-01, -5.45351378e-02, -1.55451895e+00,
         8.86828510e-01,  3.62688737e-01, -2.54282250e-01,
         1.03182708e+00,  2.52047580e-01,  1.66250990e+00,
         1.68594404e+00,  3.26855389e-01, -1.48478288e+0

In [32]:
labels[:10]

array([5, 0, 4, 0, 0, 6, 9, 5, 2, 4])

In [33]:
# funkcja to_categorical()
# konwertuje etykiety na macierz wymiaru odpowiadającego liczbie klas

from tensorflow.keras.utils import to_categorical

labels = to_categorical(labels)
labels[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [34]:
labels[0] # klasa 3 - 1 jest na miejscu odpowiadającym danej klasie w tablicy
# w pozostałych miejscach 0

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [35]:
model = Sequential()
model.add(Input(shape=(150,)))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=10, activation='softmax')) # liczba neuronów wyjścia odpowiada liczbie klas
# funkcja aktywacji softmax zwróci prawdopodobieństwo przypisania próbki do każdej z klas

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.1018 - loss: 2.8859 - val_accuracy: 0.1000 - val_loss: 2.6916
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1119 - loss: 2.5901 - val_accuracy: 0.1050 - val_loss: 2.6231
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1338 - loss: 2.4382 - val_accuracy: 0.1000 - val_loss: 2.5858
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2028 - loss: 2.2708 - val_accuracy: 0.1050 - val_loss: 2.5653
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2457 - loss: 2.1302 - val_accuracy: 0.1100 - val_loss: 2.5574
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2896 - loss: 2.0561 - val_accuracy: 0.1150 - val_loss: 2.5577
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3209 - loss: 1.9659 - val_accuracy: 0.1100 - val_loss: 2.5617
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3486 - loss: 1.9216 - val_accuracy: 0.1100 - val_loss

In [36]:
test_data = np.random.randn(10, 150)
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([[0.01100044, 0.04554664, 0.00888583, 0.1267049 , 0.13623214,
        0.25434813, 0.19213147, 0.00178496, 0.04222377, 0.18114175],
       [0.13530634, 0.0395893 , 0.00774567, 0.02808465, 0.00571216,
        0.12682305, 0.13594621, 0.27286285, 0.22113799, 0.02679179],
       [0.26276743, 0.08303569, 0.17162499, 0.03479415, 0.08906572,
        0.08501963, 0.05706808, 0.07391685, 0.03123911, 0.11146832],
       [0.08514328, 0.22074446, 0.03066057, 0.10855622, 0.07429151,
        0.11676447, 0.10258918, 0.02874525, 0.00370412, 0.22880092],
       [0.05109087, 0.21102905, 0.17760064, 0.0889773 , 0.06327748,
        0.0059707 , 0.01731631, 0.00771797, 0.3724328 , 0.0045869 ],
       [0.07301273, 0.11231122, 0.00750895, 0.39964318, 0.04009484,
        0.10497097, 0.02548629, 0.03978534, 0.11339693, 0.08378945],
       [0.05790415, 0.05123616, 0.06445325, 0.17481917, 0.21384434,
        0.01009906, 0.13711192, 0.18580768, 0.0964587 , 0.00826556],
       [0.0363996 , 0.15122531, 0.1102349

In [37]:
predictions = model.predict(test_data)
predicted_classes = np.argmax(predictions, axis=1) # ponieważ nie ma już metody predict_classes()
predicted_classes

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([5, 7, 0, 9, 8, 3, 4, 4, 8, 5])

In [38]:
# regresja

data = np.random.random((1000, 150))
labels = 50 * np.random.random(1000) # etykiety ciągłe

In [39]:
data[:3]

array([[0.22832137, 0.95247254, 0.85738373, 0.17615014, 0.14055218,
        0.31817627, 0.7835767 , 0.4012069 , 0.61230412, 0.45348677,
        0.6683934 , 0.27064837, 0.89857306, 0.26344942, 0.73177668,
        0.90994108, 0.32829538, 0.53208882, 0.63396492, 0.2958781 ,
        0.7443086 , 0.260915  , 0.82455291, 0.26682591, 0.08079219,
        0.7825137 , 0.38131805, 0.68856434, 0.42078532, 0.77912556,
        0.56356769, 0.12234451, 0.41660482, 0.75254441, 0.13133621,
        0.85819068, 0.3802474 , 0.79476256, 0.86012373, 0.79065218,
        0.55611981, 0.30975153, 0.11733137, 0.62110124, 0.18746864,
        0.14744728, 0.10356741, 0.69761437, 0.10096106, 0.15537759,
        0.3958821 , 0.39328245, 0.08538032, 0.43605089, 0.74262971,
        0.59273444, 0.88383696, 0.15131662, 0.58757946, 0.57613018,
        0.56487361, 0.72462195, 0.82286797, 0.2986424 , 0.49666216,
        0.41400699, 0.97095388, 0.35144266, 0.02998418, 0.04726354,
        0.74278558, 0.06216997, 0.10703153, 0.89

In [40]:
labels[:10]

array([37.39804094, 25.53309294, 42.64940797, 10.75061834, 37.54378222,
       36.69481111, 47.06835597, 24.45444021, 49.39121759, 21.71404399])

In [41]:
model = Sequential()
model.add(Input(shape=(150,)))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=1)) # na wejściu 1 neuron i brak funkcji aktywacji - funkcja liniowa

model.compile(optimizer='rmsprop',
              loss='mse') # nie podajemy osobno metryki

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 667.8489 - val_loss: 373.5823
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 324.1318 - val_loss: 238.8722
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 225.4484 - val_loss: 221.3500
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 215.3923 - val_loss: 221.2011
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 214.0647 - val_loss: 221.1653
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 216.5970 - val_loss: 221.3427
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 222.8554 - val_loss: 221.2897
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 211.9375 - val_loss: 221.4507
Epoch 9/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 207.1428 - val_loss: 221.4183
Epoch 10/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 222.1637 - val_loss: 221.4344
Epoch 11/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 214.8619 - val_loss: 221.5403
Epoch 12/20
25/25 ━━━━━━━━━━━

In [42]:
model = Sequential()
model.add(Input(shape=(150,)))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse']) # można też podać jako f. straty i metrykę różne metryki
              # wówczas podajemy metrykę opakowaną w listę

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 21.7602 - mse: 673.3754 - val_loss: 16.7129 - val_mse: 414.0747
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15.3933 - mse: 360.0308 - val_loss: 13.7276 - val_mse: 258.6786
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13.2086 - mse: 241.1548 - val_loss: 12.9749 - val_mse: 222.4012
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.7904 - mse: 222.2669 - val_loss: 12.8846 - val_mse: 219.7260
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13.6587 - mse: 240.3255 - val_loss: 12.8642 - val_mse: 219.4306
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.6986 - mse: 216.0462 - val_loss: 12.8304 - val_mse: 219.3992
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.8554 - mse: 219.2711 - val_loss: 12.8586 - val_mse: 219.3830
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.9313 - mse: 218.7775 - val_loss: 12.8393 - val_mse: 219.3231
Epoch 9/20
25/25 ━━━━━━

In [43]:
test_data = np.random.random((10, 150))
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step


array([[23.132961],
       [22.17499 ],
       [26.317297],
       [25.330105],
       [24.774834],
       [23.274273],
       [24.682526],
       [23.200907],
       [25.435518],
       [25.218075]], dtype=float32)